name: Unit Testing 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: static analysis
      run: cppcheck --enable=all 3_Implementation
