#TargetName : Dependencies
#<TAB>commands

Build : project_main.c converter.c
     gcc project_main.c converter.c -o converter.out

Run : converter.out
      ./converter.out

Clean:
     rm -rf *.o *.out *.i *.s 